# These are supported funding model platforms
# Replace with a single custom sponsorship URL
# custom:  https://createbrowser.github.io/AutoGetFeaturesCefSharpBrowserDesktopPC/PayPal.html 

#
#

# github: # [mohamedosama914@github.com, CreateBrowser@github.com, mohamedosama914@createbrowser.noreply.github.com, createbrowser@AutoGetFeaturesCefSharpBrowserDesktopPC]  # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2] # https://github.com/mohamedosama914
# patreon: # [mohamedosama914] # Replace with a single Patreon username
# open_collective: # [mohamedosama914] # Replace with a single Open Collective username
# ko_fi: # Replace with a single Ko-fi username
# tidelift: # C#/nuget # Replace with a single Tidelift platform-name/package-name e.g., npm/babel

#
# patreon: alexmaitland

#github: [12082147+mohamedosama914@users.noreply.github.com, mohamedosama914@users.noreply.github.com] 
#github: [12082147+mohamedosama914@users.noreply.github.com, mohamed.osama914@yahoo.com] 
#github: [mohamedosama914@users.noreply.github.com, mohamed.osama914@yahoo.com] 
#github: [12082147+mohamedosama914@users.noreply.github.com] 
#github: [mohamedosama914@users.noreply.github.com] 
#github: [mohamed.osama914@yahoo.com] 

github: mohamed.osama914@yahoo.com
yahoo: No commit message
Email: No commit message
mail: No commit message

custom: https://paypal.me/MohamedOsama914/10
