# codecov.yml
#
# .codecov.yml
#
# codecov:
#  ci:
#    - jenkins.domain.com       # add my Custom Server
#    - !jenkins.domain.com       # add my custom jenkins server
#    - !appveyor                # ignore CI builds by AppVeyor
#    - !not.this.domain.com     # ignore this domain
# https://createbrowser.github.io/AutoGetFeaturesCefSharpBrowserDesktopPC/
#

CODECOV_TOKEN="812d2fb0-1141-4645-a59b-c59fc06d7b64"
codecov:
  token: 812d2fb0-1141-4645-a59b-c59fc06d7b64
  branch: stable
# ci: - createbrowser.github.io/AutoGetFeaturesCefSharpBrowserDesktopPC       # add my Custom Server


coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project: yes
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no
